openapi: 3.0.3
info:
  title: User Signup API
  description: Create a new user account with email and password
  version: 1.0.0

paths:
  /api/auth/signup:
    post:
      summary: Register a new user account
      description: |
        Creates a new user account with the provided email and password.
        Password is hashed before storage. Returns user information on success.
      operationId: signupUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: User's email address (must be unique)
                  example: user@example.com
                password:
                  type: string
                  minLength: 8
                  maxLength: 128
                  description: User's password (will be hashed)
                  example: SecurePass123!
                name:
                  type: string
                  maxLength: 100
                  description: User's display name (optional)
                  example: John Doe
      responses:
        '201':
          description: User account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique user identifier
                    example: 550e8400-e29b-41d4-a716-446655440000
                  email:
                    type: string
                    format: email
                    description: User's email address
                    example: user@example.com
                  name:
                    type: string
                    nullable: true
                    description: User's display name
                    example: John Doe
                  created_at:
                    type: string
                    format: date-time
                    description: Account creation timestamp
                    example: 2026-01-22T10:30:00Z
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: Invalid email format
                error_code: VALIDATION_ERROR
                status_code: 400
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: Email already registered
                error_code: CONFLICT
                status_code: 409
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              example:
                detail:
                  - loc: ["body", "password"]
                    msg: Password must be at least 8 characters
                    type: value_error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: Internal server error
                error_code: INTERNAL_ERROR
                status_code: 500

components:
  schemas:
    Error:
      type: object
      required:
        - detail
        - error_code
        - status_code
      properties:
        detail:
          type: string
          description: Human-readable error message
        error_code:
          type: string
          description: Machine-readable error code
        status_code:
          type: integer
          description: HTTP status code

    ValidationError:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of the error in the request
              msg:
                type: string
                description: Error message
              type:
                type: string
                description: Error type
